name: publish

on:
  workflow_call:

permissions: {}

jobs:
  retired:
    runs-on: ubuntu-22.04
    permissions: {}
    steps:
      - name: retired-interface
        run: |
          printf 'publish interface retired' >&2
          exit 1
